# Generated by Django 4.2.2 on 2023-06-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_app', '0003_rename_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMIN', 'admin'), ('PROFESOR', 'professor'), ('STUDENT', 'student')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NONE', 'none'), ('REDOVNI', 'redovni'), ('IZVANREDNI', 'izvanredni')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enroll_app.role'),
        ),
    ]
