# Generated by Django 4.2.2 on 2023-06-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_app', '0004_role_user_status_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('program', models.TextField()),
                ('ects', models.IntegerField()),
                ('sem_redovni', models.IntegerField()),
                ('sem_izvanredni', models.IntegerField()),
                ('elective_subject', models.CharField(choices=[('DA', 'da'), ('NE', 'ne')], max_length=50)),
                ('professor', models.ForeignKey(limit_choices_to={'role__role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'enrolled'), ('PASSED', 'passed'), ('FAILED', 'failed')], default='enrolled', max_length=50)),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll_app.subject')),
            ],
        ),
    ]
