# Generated by Django 4.2.2 on 2023-06-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_app', '0006_remove_user_role_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
    ]
